name: Bump version and publish
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'package.json'

jobs:
  version-app:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Bump version and push tag
      id: changelog
      uses: TriPSs/conventional-changelog-action@v6
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        git-user-name: "github-actions[bot]"
        git-user-email: "github-actions[bot]@users.noreply.github.com"
        preset: "conventionalcommits"
        output-file: false
        skip-on-empty: false # maybe just for testing

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata for the Docker image
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: cjb13579/christmas-community

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx    
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          latest
          ${{ steps.changelog.outputs.version }}
        labels: ${{ steps.meta.outputs.labels }}

    # - name: create release
    #   uses: actions/create-release@v1
    #   if: ${{ steps.changelog.outputs.skipped == 'false' }}
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.github_token }}
    #   with:
    #     tag_name: ${{ steps.changelog.outputs.tag }}
    #     release_name: ${{ steps.changelog.outputs.tag }}
    #     body: ${{ steps.changelog.outputs.clean_changelog }}