name: Bump version
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'package.json'

jobs:
  version-app:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Bump version and push tag
      id: changelog
      uses: TriPSs/conventional-changelog-action@v6
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        preset: "conventionalcommits"
        output-file: "false"
        skip-ci: "false"
        skip-on-empty: "false" # maybe just for testing

    # - name: create release
    #   uses: actions/create-release@v1
    #   if: ${{ steps.changelog.outputs.skipped == 'false' }}
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.github_token }}
    #   with:
    #     tag_name: ${{ steps.changelog.outputs.tag }}
    #     release_name: ${{ steps.changelog.outputs.tag }}
    #     body: ${{ steps.changelog.outputs.clean_changelog }}